# PATHS: change accordingly
wav_directory: '/data/datasets/ASVoice4' # path to directory cointaining the wavs
metadata_path: '/data/datasets/ASVoice4/metadata_clean.csv'  # name of metadata file under wav_directory
log_directory: '/data/francesco/logs/transformer_tts/experiments'   # weights and logs are stored here
train_data_directory: 'transformer_tts_data'   # training data is stored here
data_config: './data_config.yaml'
aligner_config: './aligner_config.yaml'
tts_config: './tts_config.yaml'

data_name: ljspeech # raw data naming for default data reader (select function from data/metadata_readers.py)