# PATHS: change accordingly
wav_directory: '/path/to/wav_directory' # path to directory cointaining the wavs
metadata_path: '/path/to/metadata.csv'  # name of metadata file under wav_directory
log_directory: '/path/to/logs_directory'   # weights and logs are stored here
train_data_directory: 'transformer_tts_data'   # training data is stored here
data_config: 'config/data_config.yaml'
aligner_config: 'config/aligner_config.yaml'
tts_config: 'config/tts_config.yaml'

tts_config_name: tts_standard
aligner_config_name: aligner_standard
data_name: ljspeech # raw data naming for default data reader (select function from data/metadata_readers.py)